### ISSUE TITLE
Error   INFO: EXECUTION FAILURE when opening the extension

### ISSUE THREAD

**Issue by abd3** [silverbulleters/sonarqube-inject-vsc#34]
For the last month or so, we've been getting this error when opening VS Code:
Error INFO: EXECUTION FAILURE
[SonarQube support for Visual Studio Code* INFO: EXECUTION FAILURE INFO:
	INFO: Total time: 0.003slNFO: Final
Memory: 9M/31MINFO:
ERROR: Error executing  SonarLint
ERROR: Error preparing list of files to  analyze
ERROR: Caused by: /.fseventsd
ERROR: 
ERROR: To see the full stack trace of the errors, re-run SonarLint with the -e switch.
ERROR: Re-run SonarLint  using the -X switch to enable full debugging

(I'm on a Mac). 
It looks like it's trying to scan all of the files in the root of the drive like /.fseventsd instead of just scanning our local project files. Any insight??

![image](https://user-images.githubusercontent.com/11654102/36763762-3fa2365e-1bde-11e8-9dad-896f7dedcf05.png)

**Comment by nixel2007** [comment]
Hello! Did you change any sonarlint-inject settings in your workspace/user settings file?

**Comment by McPringle** [comment]
Same problem on my Mac, just after the first installation of this plugin. If you need any more info, please ask.

**Comment by abd3** [comment]
@nixel2007 I have not changed any user settings related to this plugin. My colleagues all report the same issue on both Windows and Mac.

**Comment by tandrieuxx** [comment]
Same here on Windows, I have this error on every file but no details on what causes it (I don't have the "Error preparing list of files to analyze" and "./fsevent" parts). As I use VS Code Insiders, I've tried on the regular version and it's the same.

**Comment by nixel2007** [comment]
Could you add debug flags to your plugin installation? You need to open a out/src/features/lintProvider.js, getSpawnArgs method, and add "-X" and "-e" values to args array.

Then output will be more verbose. Also you can check  the error output at dev tools console window.

**Comment by abd3** [comment]
OK, Here's the stack trace. As I read this, the issue is that it's trying
to read a file at the root of my filesystem on Mac OS and it doesn't have
permissions to read that file. Earlier on I had a different version of the
error where it was trying to read a different file at the root of my
filesystem. So it seems like somehow your extension is getting confused
about the workspace folder and is trying to scan the root of the drive




[Extension Host] INFO: EXECUTION FAILURE
INFO:
------------------------------------------------------------------------
INFO: Total time: 0.002s
INFO: Final Memory: 7M/26M
INFO:
------------------------------------------------------------------------
ERROR: Error executing SonarLint
java.lang.IllegalStateException: Error preparing list of files to analyze
at org.sonarlint.cli.analysis.SonarLint.runAnalysis(SonarLint.java:49)
at org.sonarlint.cli.Main.runOnce(Main.java:118)
at org.sonarlint.cli.Main.run(Main.java:97)
at org.sonarlint.cli.Main.execute(Main.java:188)
at org.sonarlint.cli.Main.main(Main.java:148)
*Caused by: java.nio.file.AccessDeniedException: /.fseventsd*
at
java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
at
java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
at
java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
at
java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:408)
at java.base/java.nio.file.Files.newDirectoryStream(Files.java:465)
at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:300)
at java.base/java.nio.file.FileTreeWalker.next(FileTreeWalker.java:373)
at java.base/java.nio.file.Files.walkFileTree(Files.java:2749)
at java.base/java.nio.file.Files.walkFileTree(Files.java:2785)
at org.sonarlint.cli.InputFileFinder.collect(InputFileFinder.java:89)
at org.sonarlint.cli.analysis.SonarLint.runAnalysis(SonarLint.java:47)
... 4 more

**Comment by nixel2007** [comment]
Crap, it doesn't trace info messages before first error line.

**Comment by abd3** [comment]
I can set up time with you to debug if you want. Get me on Hangouts at
abd3721@gmail.com or text me at 1-619-721-3721  we can step through
debugging it.

**Comment by tandrieuxx** [comment]
I don't know if my problem is the same...

`INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 0.654s
INFO: Final Memory: 10M/162M
INFO: ------------------------------------------------------------------------
ERROR: Error executing SonarLint
org.sonar.squidbridge.api.AnalysisException: Unable to analyse file: d:/shared/addons/lau-odoo/pos_event/static/src/js/pos_event.js
	at org.sonar.plugins.javascript.JavaScriptSquidSensor.analyse(JavaScriptSquidSensor.java:175)
	at org.sonar.plugins.javascript.JavaScriptSquidSensor.analyseFiles(JavaScriptSquidSensor.java:134)
	at org.sonar.plugins.javascript.JavaScriptSquidSensor.execute(JavaScriptSquidSensor.java:343)
	at org.sonarsource.sonarlint.core.analyzer.sensor.NewSensorsExecutor.executeSensor(NewSensorsExecutor.java:72)
	at org.sonarsource.sonarlint.core.analyzer.sensor.NewSensorsExecutor.execute(NewSensorsExecutor.java:63)
	at org.sonarsource.sonarlint.core.analyzer.sensor.PhaseExecutor.execute(PhaseExecutor.java:36)
	at org.sonarsource.sonarlint.core.container.analysis.AnalysisContainer.doAfterStart(AnalysisContainer.java:141)
	at org.sonarsource.sonarlint.core.container.ComponentContainer.startComponents(ComponentContainer.java:125)
	at org.sonarsource.sonarlint.core.container.ComponentContainer.execute(ComponentContainer.java:110)
	at org.sonarsource.sonarlint.core.container.standalone.StandaloneGlobalContainer.analyze(StandaloneGlobalContainer.java:144)
	at org.sonarsource.sonarlint.core.StandaloneSonarLintEngineImpl.analyze(StandaloneSonarLintEngineImpl.java:93)
	at org.sonarlint.cli.analysis.StandaloneSonarLint.doAnalysis(StandaloneSonarLint.java:53)
	at org.sonarlint.cli.analysis.SonarLint.runAnalysis(SonarLint.java:59)
	at org.sonarlint.cli.Main.runOnce(Main.java:118)
	at org.sonarlint.cli.Main.run(Main.java:97)
	at org.sonarlint.cli.Main.execute(Main.java:188)
	at org.sonarlint.cli.Main.main(Main.java:148)
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:212)
	at com.google.common.io.ByteSource$AsCharSource.<init>(ByteSource.java:443)
	at com.google.common.io.ByteSource$AsCharSource.<init>(ByteSource.java:438)
	at com.google.common.io.ByteSource.asCharSource(ByteSource.java:74)
	at com.google.common.io.Files.asCharSource(Files.java:226)
	at com.google.common.io.Files.toString(Files.java:274)
	at com.sonar.sslr.api.typed.ActionParser.parse(ActionParser.java:91)
	at org.sonar.javascript.parser.JavaScriptParser.parse(JavaScriptParser.java:43)
	at org.sonar.javascript.parser.JavaScriptParser.parse(JavaScriptParser.java:29)
	at org.sonar.plugins.javascript.JavaScriptSquidSensor.analyse(JavaScriptSquidSensor.java:163)
	... 16 more`

**Comment by nixel2007** [comment]
@tandrieuxx nope. Your problem comes from js-plugin for sonarqube. try to update included jar with newer version or use a connected mode.

**Comment by abd3** [comment]
@nixel2007 have you been able to reproduce this? We have this extension installed by hundreds of our developers and it's generating a steady stream of error messages for them.

**Comment by nixel2007** [comment]
@abd3, not yet, sorry. And I can't find time for this before next Tuesday :(

**Comment by abd3** [comment]
@nixel2007 any chance you've had a chance to look at this? Anything we can do to help?

**Comment by abd3** [comment]
Any update on this. This is killing us. Generates errors for every file we open.

**Comment by valepu** [comment]
Same error on Linux, except instead of "/.fseventsd" it's "/home/user/.gvfs"

**Comment by allustin** [comment]
@valepu @jcampanaaxa i will try to fix it

**Comment by JohhnyP** [comment]
Greetings.
Any progress with this?

**Comment by allustin** [comment]
@JohhnyP yes - release in this week with hotfix

**Comment by abd3** [comment]
@allustin any update?

**Comment by allustin** [comment]
@abd3 yup

migrating to sonarlint-core 3.8 and sonarcli 2.2 (archived ;-)

we fork the core https://github.com/silverbulleters-research/sonarlint-core/tree/feature/add-bsl-plugin to add some plugin as trusted

we fork cli and fix some test - server specs are changed https://github.com/silverbulleters-research/sonarlint-cli/tree/feature/console-analysis

the end of fix is close ;-)

**Comment by abd3** [comment]
Thanks for working on this. I see that SilverBulleters created this repo in August 2016. At that time there was no official VS Code extension for SonarQube. In May 2017, SonarSource began publishing a version of [SonarLint for VS Code](https://github.com/SonarSource/sonarlint-vscode/commits/master?after=61e6adafddae901a8e2649d2d2fc151427c85dc9+104). They are actively committing to that project, and we're inclined to move to that official extension. #43 mentions concern that the CLI that this is based on is now deprecated.
Are there features or benefits that this extension provides that are not included in the official extension?

**Comment by allustin** [comment]
@abd3 we need some additional plugins for vscode - java, C#, kotlin, bsl, gherkin, C++(Community Version) in connected mode

may be we also migrate for official extension if that pull request are approved 
https://github.com/morganfogg/sonarlint-vscode/commit/f41e7654dffc89529cf22cd818d7fcbbc2f77775

**Comment by bestii** [comment]
Any update on this issue? I am facing the same

**Comment by narendarnaik** [comment]
I added SonarLint plugin in VSCode it was running successfully.
After that I also added SonarQube plugin in VSCode...then same above 
<img width="341" alt="sonarqube issue" src="https://user-images.githubusercontent.com/26519417/45155099-55279380-b1c9-11e8-9126-f60776c59538.PNG">
error is throwing!!

**Comment by narendarnaik** [comment]
I attempted re-installing both SonarLint and Sonarqube….same result! Please update the solution for same...

**Comment by goneglobal** [comment]
I get the same errors for SonarLint & SonarQube on Mac using VSCode :(

**Comment by samuel-ye** [comment]
Workaround for my VSC 1.28 + Sonarqube Inject 2.1.0:
1. checked out and built sonarlint-cli console branch according to allustin's post (mine mac 64bit and Java1.8.0 pre-built [one](https://github.com/samuel-ye/sonarlint-cli/releases/download/2.2-console/sonarlint-cli-2.2-SNAPSHOT.zip) )

1. replace old sonarlint-cli under tools folder in sonarqube-inject-vsc extension

1. reload VSC, do sonarqube inject analysis in connected mode and wait for sonarlint messages

**Comment by shmilyvidian** [comment]
'SonarJS' skipped because there is no related file in current project, how to solve it?
