### ISSUE TITLE
SonarQube just stopped working

### ISSUE THREAD

**Issue by tandrieuxx** [silverbulleters/sonarqube-inject-vsc#35]
Hello,
I don't know since when, but SonarQube just doesn't work anymore.
With Javascript I had an "EXECUTION FAILURE" error that I fixed by putting an up-to-date .jar in `[...]\silverbulleters.sonarqube-inject-2.1.0\tools\sonarlint-cli\plugins`. Now it seems to work fine but only for JS files.
On Python side, I have no error at all and nothing in the "problems" window (even if I add some code after a return, etc.). Updating the Python plugin haven't changed anything.
A few minutes ago I was editing a text file (.puml, nothing that should be analyzed by Sonar), and got this error : 
```
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 0.789s
INFO: Final Memory: 6M/134M
ERROR: Error executing SonarLint
INFO: ------------------------------------------------------------------------
java.lang.IllegalStateException: Unable to create root temp directory C:\Program Files\Microsoft VS Code Insiders\.sonarlint\.sonartmp
	at org.sonarsource.sonarlint.core.container.analysis.AnalysisTempFolderProvider.provide(AnalysisTempFolderProvider.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.picocontainer.injectors.MethodInjector.invokeMethod(MethodInjector.java:129)
	at org.picocontainer.injectors.MethodInjector.access$000(MethodInjector.java:39)
	at org.picocontainer.injectors.MethodInjector$2.run(MethodInjector.java:113)
	at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
	at org.picocontainer.injectors.MethodInjector.decorateComponentInstance(MethodInjector.java:120)
	at org.picocontainer.injectors.CompositeInjector.decorateComponentInstance(CompositeInjector.java:58)
	at org.picocontainer.injectors.Reinjector.reinject(Reinjector.java:142)
	at org.picocontainer.injectors.ProviderAdapter.getComponentInstance(ProviderAdapter.java:96)
	at org.picocontainer.DefaultPicoContainer.instantiateComponentAsIsStartable(DefaultPicoContainer.java:1034)
	at org.picocontainer.DefaultPicoContainer.addAdapterIfStartable(DefaultPicoContainer.java:1026)
	at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1003)
	at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
	at org.sonarsource.sonarlint.core.container.ComponentContainer.startComponents(ComponentContainer.java:124)
	at org.sonarsource.sonarlint.core.container.ComponentContainer.execute(ComponentContainer.java:110)
	at org.sonarsource.sonarlint.core.container.standalone.StandaloneGlobalContainer.analyze(StandaloneGlobalContainer.java:144)
	at org.sonarsource.sonarlint.core.StandaloneSonarLintEngineImpl.analyze(StandaloneSonarLintEngineImpl.java:93)
	at org.sonarlint.cli.analysis.StandaloneSonarLint.doAnalysis(StandaloneSonarLint.java:53)
	at org.sonarlint.cli.analysis.SonarLint.runAnalysis(SonarLint.java:59)
	at org.sonarlint.cli.Main.runOnce(Main.java:118)
	at org.sonarlint.cli.Main.run(Main.java:97)
	at org.sonarlint.cli.Main.execute(Main.java:188)
	at org.sonarlint.cli.Main.main(Main.java:148)
Caused by: java.nio.file.AccessDeniedException: C:\Program Files\Microsoft VS Code Insiders\.sonarlint
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:504)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:767)
	at org.sonarsource.sonarlint.core.container.analysis.AnalysisTempFolderProvider.provide(AnalysisTempFolderProvider.java:43)
	... 26 more
```

I use VS Code Insiders, but it's not better with the regular version...

**Comment by nixel2007** [comment]
Hello. Looks like your bug is similar to #34. Need to investigate, why vsc works with wrong paths.
