### ISSUE TITLE
command 'sonarqube-inject.analyzeProject' not found

### ISSUE THREAD

**Issue by clicman** [silverbulleters/sonarqube-inject-vsc#9]
Installed extension on VScode 1.10.1
And cannot run analyse with ```command 'sonarqube-inject.analyzeProject' not found``` error. What's wrong?

**Comment by nixel2007** [comment]
When you run this extension first time, you should see the notification bar (at the top of the window) with "sonarlint is not found, download started". Do you see the second message with "installation complete"?

**Comment by clicman** [comment]
Yes, after some it says what its installed.

**Comment by nixel2007** [comment]
And command still not working? Try restart vscode, please.

**Comment by nixel2007** [comment]
P. S. Можно по-русски

**Comment by clicman** [comment]
Ok :)
Ну не работает. Посмотрел в директории естеншона, тул скачался, но ошибка осталась. Рестарты не помогают. Может дать какую-нибудь дебаг-инфу?
![image](https://cloud.githubusercontent.com/assets/1079535/23710823/959ed766-0450-11e7-893f-068612e69fc4.png)

**Comment by nixel2007** [comment]
Есть ли что-то в консоли в дев-тулзах? f1 - toggle developer tools.

**Comment by nixel2007** [comment]
На вскидку - команды регистрируются, когда экстеншн понимает, что sonarlint-cli распакован и установлен корректно - https://github.com/silverbulleters/sonarqube-inject-vsc/blob/master/src/extension.ts#L21

Возможно вот здесь какая-то засада.

Если в консоли ничего не будет, то предлагаю подебажить экстеншн удаленно :)

**Comment by clicman** [comment]
Хмммм... а вот сразу вопрос на вскидку. await он работает в ноде < 7? Может у меня просто нода старая?

**Comment by nixel2007** [comment]
Тайпскриптовский await компилируется в нативный yield (да еще и с генератором) под es6. А он есть. Если заглянуть в экстеншн, в папку out/src, то можно увидеть этот ад.

**Comment by nixel2007** [comment]
Плюс в vsc встроена своя нода.

**Comment by clicman** [comment]
Оххохох :) Сегодня вечером гляну и отпишусь, теперь хотя бы понятно где смотреть :)

**Comment by nixel2007** [comment]
Напишу тогда сразу про отладку - 
* установить ноду
* склонировать исходники
* npm install в папке с исходниками
* открыть в vsc папке с исходниками
* запустить отладку (Launch extention) на вкладке Отладка/Debug

Должны работать точки останова в extension.ts.

Обращаю внимание, что f10/f11 после строки с await работает не интуитивно - для отладки такого куска:
```typescript
a = await someFunc();
console.log(a);
```

стоит ставить 2 точки останова и переходить от первой ко второй по f5.

Если в более-менее рабочее время, то можно попробовать подконнектится тим-вьювером/скайпом/зумом и парно поглядеть.

**Comment by clicman** [comment]
Окей. Спасибо за информацию. Попробую сам, не получится буду призывать помощь :)

**Comment by clicman** [comment]
Воу....
```
[Extension Host] Here is the error stack:  Error: spawn EACCES
    at exports._errnoException (util.js:1026:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at Object.exports.spawn (child_process.js:392:9)
    at spawn (/home/sidochenko/.vscode/extensions/silverbulleters.sonarqube-inject-1.1.4/node_modules/cross-spawn/index.js:17:18)
    at LintProvider.doLint (/home/sidochenko/.vscode/extensions/silverbulleters.sonarqube-inject-1.1.4/out/src/features/lintProvider.js:47:29)
    at LintProvider.activate (/home/sidochenko/.vscode/extensions/silverbulleters.sonarqube-inject-1.1.4/out/src/features/lintProvider.js:21:14)
    at addSubscriptions (/home/sidochenko/.vscode/extensions/silverbulleters.sonarqube-inject-1.1.4/out/src/extension.js:70:12)
    at /home/sidochenko/.vscode/extensions/silverbulleters.sonarqube-inject-1.1.4/out/src/extension.js:34:9
    at next (<anonymous>)
    at fulfilled (/home/sidochenko/.vscode/extensions/silverbulleters.sonarqube-inject-1.1.4/out/src/extension.js:4:58)
```

**Comment by clicman** [comment]
В общем дело такое, надо chmod + x делать на исполняемый файл.

**Comment by nixel2007** [comment]
точно, мне же говорил про это кто-то месяц назад... Попробуй подготовить пулл-реквест.

**Comment by clicman** [comment]
ок. на днях займусь.

**Comment by nixel2007** [comment]
> Попробуй 

Очепятка, попробуЮ :)

**Comment by OlivierDupre** [comment]
Well... please could you translate? What was the solution?

Cheers,
Olivier

**Comment by OlivierDupre** [comment]
OK. Found the solution. We must make sonarlint executable in the following path on GNU/Linux : 
`.vscode/extensions/silverbulleters.sonarqube-inject-1.3.0/tools/sonarlint-cli/bin/`

Just need to run `chmod +x sonarlint`

**Comment by nixel2007** [comment]
@OlivierDupre hello! is the bug reoccure in 1.3.0? I've changed the installation process so sonarlint-cli no more loaded and installed in runtime but packaged with extension itself.
But I prepare package on win, so I could forgot about +x thing.

Could you test repacked dev version, please (I'll link it here in a few mins)?

**Comment by OlivierDupre** [comment]
@nixel2007 Priviet Nikita. Yes, the bug reoccure. I'll try your new pack, no problem.

Cheers.

**Comment by nixel2007** [comment]
@OlivierDupre please check this version https://github.com/silverbulleters/sonarqube-inject-vsc/releases/download/v1.3.1-RC8/sonarqube-inject-1.3.1.vsix

**Comment by OlivierDupre** [comment]
Hey man. Sorry it's still not working. The binary has the +x rights, but when I'm running `SonarQube Inject: Create global config with credentials to servers` it fails with the very simple message `Error. INFO: EXECUTION FAILURE` No clue of what's happening. Where are the logs? How can I turn them more verbose?
By the way, it does not create the `~/.sonarlint` folder.

PS: Should I download separately the `sonarlint` plugin? I though your plugin was going to do it directly.

**Comment by nixel2007** [comment]
Could you check Developer tools (f1 - Developer: toogle dev tools), open console tab. you should see something like this:
![image](https://user-images.githubusercontent.com/1132840/28663610-8bf6a9fc-72c6-11e7-83e6-64ec0fded490.png)


Also you should see error message if you hover the error bar at the top:
![image](https://user-images.githubusercontent.com/1132840/28663642-9f16debc-72c6-11e7-81cc-520489c1a3a5.png)

**Comment by nixel2007** [comment]
> PS: Should I download separately the sonarlint plugin? I though your plugin was going to do it directly.

Nope, this plugin (sonarqube-inject) and sonarlint plugin from SonarSource are different implementation of this kind of analizys in VSC

**Comment by OlivierDupre** [comment]
OK. So here is the result:

> INFO: ------------------------------------------------------------------------
> INFO: Total time: 416985:30:35.301s
> INFO: Final Memory: 1M/119M
> INFO: ------------------------------------------------------------------------
> ERROR: Error executing SonarLint
> ERROR: Found project binding but there is no SonarQube server configured in: /home/odupre/.sonarlint/conf/global.json
> ERROR: 
> ERROR: To see the full stack trace of the errors, re-run SonarLint with the -e switch.
> ERROR: Re-run SonarLint using the -X switch to enable full debug logging.

Then it complains that `~/.sonarlint/conf` does not exist and it can't `mkdir` it. Maybe you should just add the `-p` option to your `mkdir` command so it creates the whole tree down to the directory you need.

> extensionHost.ts:320[Extension Host] INFO: EXECUTION FAILURE
> INFO: ------------------------------------------------------------------------
> INFO: Total time: 416985:30:35.301s
> INFO: Final Memory: 1M/119M
> INFO: ------------------------------------------------------------------------
> ERROR: Error executing SonarLint
> ERROR: Found project binding but there is no SonarQube server configured in: /home/odupre/.sonarlint/conf/global.json
> ERROR: 
> ERROR: To see the full stack trace of the errors, re-run SonarLint with the -e switch.
> ERROR: Re-run SonarLint using the -X switch to enable full debug logging.
> messageService.ts:125INFO: EXECUTION FAILURE
> INFO: ------------------------------------------------------------------------
> INFO: Total time: 416985:30:35.301s
> INFO: Final Memory: 1M/119M
> INFO: ------------------------------------------------------------------------
> ERROR: Error executing SonarLint
> ERROR: Found project binding but there is no SonarQube server configured in: /home/odupre/.sonarlint/conf/global.json
> ERROR: 
> ERROR: To see the full stack trace of the errors, re-run SonarLint with the -e switch.
> ERROR: Re-run SonarLint using the -X switch to enable full debug logging.
> e.doShow @ messageService.ts:125
> extensionHost.ts:320[Extension Host] Child process connected on port 55282
> messageService.ts:125 Objectcode: "ENOENT"errno: -2path: "/home/odupre/.sonarlint/conf/global.json"syscall: "open"__proto__: Object
> e.doShow @ messageService.ts:125
> e.show @ messageService.ts:104
> e.resume @ messageService.ts:63
> (anonymous) @ workbench.ts:945
> e.invoke @ callbackList.ts:63
> e.fire @ event.ts:123
> (anonymous) @ quickOpenController.ts:513
> messageService.ts:125 Objectcode: "ENOENT"errno: -2path: "/home/odupre/.sonarlint/conf"syscall: "mkdir"__proto__: Object__defineGetter__: __defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get __proto__: __proto__()set __proto__: __proto__()
> e.doShow @ messageService.ts:125
> e.show @ messageService.ts:104
> e.resume @ messageService.ts:63
> (anonymous) @ workbench.ts:945
> e.invoke @ callbackList.ts:63
> e.fire @ event.ts:123
> (anonymous) @ quickOpenController.ts:513

**Comment by nixel2007** [comment]
ah, i see, i don't create .sonarlint itself. thanks for point this!

next RC incoming

**Comment by nixel2007** [comment]
@OlivierDupre link to new RC - https://github.com/silverbulleters/sonarqube-inject-vsc/releases/download/v1.3.1-RC9/sonarqube-inject-1.3.1.vsix

**Comment by OlivierDupre** [comment]
That's good. It's working. Thanks guy.

**Comment by nixel2007** [comment]
Okey, i'll publish it to marketplace soon. Thanks!

**Comment by Tenmak** [comment]
Hey, I have a different problem, I'm using VS Code on Windows with SonarQube and SonarLint extensions and the commands are not working : `bash: SonarQube: command not found`.

Could this be because of the fact that I use GIT BASH in the VSCODE integrated terminal ?

Thanks

**Comment by nixel2007** [comment]
@Tenmak hello! Could you provide some logs from dev tools in vscode?

**Comment by nixel2007** [comment]
P. S. AFAIK vscode must be opened in "directory" mode. Also file with extension of supported language (see list in Readme) should be opened to activate the extension.

**Comment by Tenmak** [comment]
Actually it was just that I tried to execute the commands from the integrated terminal instead of the commands from VS Code... I went full retard after 10 hours of work... I'm ashamed...
Thanks for your fast response and sorry for the inconvenience.
